language: rust
cache: cargo
rust:
  - stable

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test

notifications:
  irc:
    channels:
     - "ircs://irc.rpis.ec:6697/#test"
